if(APM_SYSTEM_UTILS_INCLUDE_GUARD)
	APM_message(DEBUG "APM system utils already included.")
else()
	set(APM_SYSTEM_UTILS_INCLUDE_GUARD ON)

  function(APM_get_OS a_APM_result)
    if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
      set(a_APM_result "windows" PARENT_SCOPE)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
      set(a_APM_result "linux" PARENT_SCOPE)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
      set(a_APM_result "mac" PARENT_SCOPE)
    endif()
  endfunction()

  function(APM_get_arch a_APM_result)
    if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
      set(a_APM_result "windows" PARENT_SCOPE)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
      set(a_APM_result "linux" PARENT_SCOPE)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
      set(a_APM_result "mac" PARENT_SCOPE)
    endif()
  endfunction()

endif()
