if(IPM_SYSTEM_UTILS_INCLUDE_GUARD)
	inquire_message(DEBUG "IPM system utils already included.")
else()
	set(IPM_SYSTEM_UTILS_INCLUDE_GUARD ON)

  function(IPM_get_OS a_IPM_result)
    if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
      set(a_IPM_result "windows" PARENT_SCOPE)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
      set(a_IPM_result "linux" PARENT_SCOPE)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
      set(a_IPM_result "mac" PARENT_SCOPE)
    endif()
  endfunction()

  function(IPM_get_arch a_IPM_result)
    if(${CMAKE_SYSTEM_NAME} MATCHES "Windows")
      set(a_IPM_result "windows" PARENT_SCOPE)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
      set(a_IPM_result "linux" PARENT_SCOPE)
    elseif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
      set(a_IPM_result "mac" PARENT_SCOPE)
    endif()
  endfunction()

endif()
